import React, { useEffect, useState } from "react";

import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import styles from "../../styles/NavComponent.module.css";
import { useDispatch, useSelector } from "react-redux";
import { NavComponent } from "./NavComponent";
//import withRedux from "next-redux-wrapper";
import { useRouter } from "next/router";
import { login, startChecking } from "../../actions/auth";

export default function AppLayout({ children }) {
  const dispatch = useDispatch();

  const { auth } = useSelector((state) => state);

  const router = useRouter();
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  const [checking, setCheking] = useState(true);
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    //dispatch(startChecking());
    console.log(auth);
    setCheking(false);
  }, [dispatch, setCheking, setIsLoggedIn]);

  // if (checking) {
  //   return <h1>Espere...</h1>;
  // }

  if (router.pathname == "/login") {
    return <>{children}</>;
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {router.pathname == "/login" ? (
          <>{children}</>
        ) : (
          <div className={styles.wrapper}>
            <NavComponent />
            <div className="contentcomponent">{children}</div>
          </div>
        )}
      </>
    );
  }
}
